version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - polaris-network
    volumes:
      - sqlvolume:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    networks:
      - polaris-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PolarisDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;

networks:
  polaris-network:

volumes:
  sqlvolume:
