// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.NetworkMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ARFCN")
                        .HasColumnType("integer");

                    b.Property<double?>("ActualFrequencyMhz")
                        .HasColumnType("double precision");

                    b.Property<string>("CellId")
                        .HasColumnType("text");

                    b.Property<double?>("ECNO")
                        .HasColumnType("double precision");

                    b.Property<string>("FrequencyBand")
                        .HasColumnType("text");

                    b.Property<int?>("Lac")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NetworkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PLMNId")
                        .HasColumnType("text");

                    b.Property<int?>("RSCP")
                        .HasColumnType("integer");

                    b.Property<int?>("RSRP")
                        .HasColumnType("integer");

                    b.Property<int?>("RSRQ")
                        .HasColumnType("integer");

                    b.Property<int?>("RXLEV")
                        .HasColumnType("integer");

                    b.Property<int?>("Rac")
                        .HasColumnType("integer");

                    b.Property<int>("SignalStrength")
                        .HasColumnType("integer");

                    b.Property<int?>("Tac")
                        .HasColumnType("integer");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("NetworkMeasurements");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NetworkInformationId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NetworkInformationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.NetworkMeasurement", "NetworkInformation")
                        .WithMany()
                        .HasForeignKey("NetworkInformationId");

                    b.Navigation("NetworkInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
